name: publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 📸 Calculate commit hash
        id: sha
        uses: pr-mpt/actions-commit-hash@v2

      - name: 🔨 Prepare Bun environment
        uses: oven-sh/setup-bun@v1

      - name: 🎉 Install project dependencies
        run: bun i

      - name: 🚀 Deploy workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
            ASSETS_CLIENT_ID
            ASSETS_CLIENT_SECRET
            ASSETS_TENANT_ID
            ASSETS_MANIFESTS
        env:
          ASSETS_CLIENT_ID: ${{ secrets.ASSETS_CLIENT_ID }}
          ASSETS_CLIENT_SECRET: ${{ secrets.ASSETS_CLIENT_SECRET }}
          ASSETS_TENANT_ID: ${{ secrets.ASSETS_TENANT_ID }}
          ASSETS_MANIFESTS: ${{ secrets.ASSETS_MANIFESTS }}
          ANALYTICS_MEASUREMENT_ID: ${{ secrets.ANALYTICS_MEASUREMENT_ID }}
          ANALYTICS_API_SECRET: ${{ secrets.ANALYTICS_API_SECRET }}
          IS_PROD: true
